project:
  type: book
  output-dir: docs

#project:
#  type: website
#  output-dir: docs


book:
  title: "Kenai Mountains to Sea: Using Thermal Infrared Imagery to Implement Long-Term Salmon Conservation"
  author: "Sue Mauger (Cook Inletkeeper), Marie McCarty and Lauren Rusin (Kachemak Heritage Land Trust), Benjamin Meyer (Kenai Watershed Forum)"
  date: "January 23, 2023"
  chapters:
    - acknowledgements.qmd
    - index.qmd
    - intro.qmd
    - project_map.qmd
    - thermal_imagery_data.qmd
    - temperature_loggers.qmd
    - Applications.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - temp_logger_data_prep.qmd


  repo-url: https://github.com/Kenai-Watershed-Forum/kenai_thermal_imagery_v2
  search:
    location: sidebar
    type: textbox
  downloads: [docx]


bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
  #  documentclass: scrreprt
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github

editor: visual

prefer-html: true

