#project:
#  type: book

project:
  type: website
  output-dir: docs


book:
  title: "Kenai Thermal Imagery"
  author: "Benjamin Meyer"
  date: "11/18/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - project_map.qmd
    - thermal_imagery_data.qmd
    - temperature_loggers.qmd
    - Applications.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - temp_logger_data_prep.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
  #  documentclass: scrreprt
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github

editor: visual

prefer-html: true

