# Summary

Overall summary statement/discussion paragraph here ...
See Mountains to Sea 

## General Recommendations by Stream Corridor

The following are general observations regarding conservation potential for each of the stream corridors in this study. For more details on land ownership and watershed-specific conservation opportunities, see the Mountains to Sea report


```{r echo = F}
# load
library(tidyverse)

# what are the assessed values and sizes of private parcels with features in each of the corridors?

tbl1 <- read.csv("output/tbl1_parcel_data.csv")

bc_private_vals <- tbl1 %>%
  filter(Stream_Name == "Beaver Creek" & Owner_Type == "PRIVATE")
```


### Beaver Creek

Beaver Creek runs a total of 21.8 river miles before meeting the Kenai River, with 4.0 of those miles in the lower section outside the Kenai National Wildlife Refuge.

Land ownership in the lower Beaver Creek corridor can be described as very parcelized, with the majority of parcels that are directly adjacent to the creek in private ownership (20 of 28), most of them accessible via Beaver Loop road. In our work, we found that 21 of these parcels contained cold water refugia features (Figure 3.1).






### Funny River

"Lots of state ownership, only 7 private parcels"

### Moose River

"Too parcelized for meaningful land acquisition?

### Crooked Creek

"very parcelized"




muhlfield 2021 https://www.nature.com/articles/s41558-021-01013-w

armstrong 2021 https://www.nature.com/articles/s41558-021-00994-y

lessons from kenai decision support tool

link to google doc for future collab

https://gis.audubon.org/kenai/

https://gis.audubon.org/kenai/documentation/KenaiDecisionSupportTool_UsersManual_9Jan2014.pdf

VII.	Objectives
•	Identify areas of cold water refugia within four streams on the Kenai Peninsula using TIR imagery
•	Initiate discussion with landowners about potential land conservation efforts

spreadsheet of thermal features available to project managers only at the moment to presver landowner privacy

example of initiating conversaion: sgc
