---
title: "Water Temperature Loggers"
editor: visual
---

```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
# clear environment
rm(list=ls())

# load packages
library(bookdown)
library(tidyverse)
library(googlesheets4)
library(lubridate)
library(readr)
library(readxl)
library(writexl)
library(hms)
library(plotly)
library(DT)
library(xlsx)
library(leaflet)
library(DT)
library(ggpubr)
library(ggpmisc)
library(plotrix)
library(packrat)
library(foreign)

# set plotting themes

## geom_col plots theme
col_theme <- theme(axis.title = element_text(size = 14, face = "bold"),
                   strip.text = element_text(size = 14, face = "bold"),
                   legend.title = element_text(size = 14, face = "bold"),
                   legend.text = element_text(size = 14),
                   axis.text = element_text(size = 14))

## geom_points plots theme
points_theme <- theme(axis.title = element_text(size = 14, face = "bold"),
                   strip.text = element_text(size = 14, face = "bold"),
                   legend.title = element_text(size = 14, face = "bold"),
                   legend.text = element_text(size = 14),
                   axis.text = element_text(size = 11, face = "bold"),
                   title = element_text(size = 18))

# function to exclude multiple items per column
'%ni%' <- Negate('%in%')

# clarify select function
select <- dplyr::select
```

## Introduction

In order to supplement aerial thermal infrared imagery and cold-feature ground truthing data, we deployed water temperature loggers in the lower reach of each study stream to collect continuous time series of water temperature. We used Onset HOBO Temp Pro V2 loggers, deployed and maintained according to published regional standards [@mauger2015a].

This section describes methods to visualize and perform basic quality checks on continuous temperature loggers deployed in the study streams. All data files (.csv) used in these analyses can be downloaded from this project's [GitHub repository](https://github.com/Kenai-Watershed-Forum/kenai_thermal_imagery/tree/master/input).

## Locations

See the Project Map (Section 2) section of this report for locations of water temperature logger sites. The ArcGIS Online layer titled, "Water Temperature Logger Sites" displays these locations.

Locations will also be reflected in the Alaska Center for Conservation Science's AKOATS map ([Alaska Online Aquatic Temperature Site](https://accs.uaa.alaska.edu/aquatic-ecology/akoats/))[^temperature_loggers-1] in Spring 2023.

[^temperature_loggers-1]: https://accs.uaa.alaska.edu/aquatic-ecology/akoats/

## Additional Data Preparation

Some water temperature time series downloaded from loggers required additional examination in order to prepare them for submission to AKOATS. See Appendix A, Temperature Logger Data Preparation for additional details.

<br>

\newpage
